receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  # Export logs to Loki. The endpoint is the push API of Loki.
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  # Export metrics using Prometheus remote write. Make sure your Prometheus
  # instance is configured to accept remote writes on this endpoint.
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]

